# Copyright 2020 Mesosphere, Inc
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.14.4

LABEL name=tf-kubernetes-configmap-backend-dev

# whois is needed for mkpasswd...
RUN apt-get update && \
    apt-get install -y whois zip

ENV HOME=/tmp

ENV DOCKER_VERSION 19.03.11
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz | \
    tar xz -C /usr/bin --strip-components=1 docker/docker

ARG OS_PLATFORM
ARG DOCKER_GID
RUN if [ "$OS_PLATFORM" = "darwin" ] ; then groupadd -r docker; else groupadd docker -g ${DOCKER_GID}; fi

ENV INCONTAINER=yes
