name: Build
on:
  push:
    branches: 
    - master
    tags:
    - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Docker images
      run: make docker.build

    - name: Docker login
      if: startsWith(github.ref, 'refs/tags')
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker push release
      if: startsWith(github.ref, 'refs/tags')
      run: make docker.push

